name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'
      - '**/go.mod'

jobs:
  prepr-check:
    uses: Azure/tfmod-scaffold/.github/workflows/tfvm_e2e.yaml@oidc